Add missed functions of libgio in system.gyp
Without this, it causes the following build error on Linux.
````
../../net/proxy/proxy_config_service_linux.cc:819:24: error: no member named 'glib_check_version' in 'LibGioLoader'
    if (libgio_loader_.glib_check_version(2, 35, 0)) {
        ~~~~~~~~~~~~~~ ^
../../net/proxy/proxy_config_service_linux.cc:820:22: error: no member named 'g_type_init' in 'LibGioLoader'
      libgio_loader_.g_type_init();
      ~~~~~~~~~~~~~~ ^
````